#!/bin/sh
# File generated by ocamlbuild

cd /home/jvc/oc/src

rm -f ast.cmi
rm -f calc.cmi
rm -f calc.cmo
rm -f hello.cmi
rm -f hello.cmo
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
rm -f parser.mli
rm -f scanner.cmi
rm -f scanner.cmo
rm -f scanner.ml
# Also clean the script itself
rm -f /home/jvc/oc/src/_build/sanitize.sh
